from pathlib import Path
import base64,zlib
root=Path(__file__).parent
parts=[(root/f"v107_payload_{i}.txt").read_text().strip() for i in range(1,6)]
if len(parts[0]) == 3799:
    parts[0]=parts[0].replace('O+jXNg829iGy','O+jXNgA829iGy',1)
lengths=[len(x) for x in parts]
print('v1.0.7 payload lengths:', lengths, 'total=', sum(lengths))
if lengths != [3800,3800,3800,3800,468]:
    raise SystemExit(f'Unexpected v1.0.7 payload lengths: {lengths}')
data=''.join(parts)
exec(zlib.decompress(base64.b64decode(data)).decode())

# V08 checkout is generated by the payload while Ink is private to V100Screens.kt.
v08=Path('android-v0.1/app/src/main/java/ro/autoid/app/V08Screens.kt')
s=v08.read_text().replace('Ink','Color(0xFF101828)')
v08.write_text(s)
print('Normalized v1.0.7 checkout color scope')
