from pathlib import Path

# Versions
p=Path('android-v0.1/app/build.gradle.kts'); s=p.read_text(); s=s.replace('versionCode = 12900','versionCode = 13000').replace('versionName = "1.0.26"','versionName = "1.0.27"'); p.write_text(s)
p=Path('android-v0.1/app/src/main/java/ro/autoid/app/data/AutoIdApi.kt'); s=p.read_text(); s=s.replace('AutoID-Android/1.0.26','AutoID-Android/1.0.27')

# Order parsing/models actions
models=Path('android-v0.1/app/src/main/java/ro/autoid/app/data/Models.kt'); m=models.read_text()
m=m.replace('data class Order(val id:Long,val number:String,val status:String,val total:String,val dateCreated:String,val statusCode:String="",val trackingNumber:String="",val trackingUrl:String="",val carrier:String="",val reviewConsent:Boolean=false)',
'''data class Order(val id:Long,val number:String,val status:String,val total:String,val dateCreated:String,val statusCode:String="",val trackingNumber:String="",val trackingUrl:String="",val carrier:String="",val reviewConsent:Boolean=false,val canPay:Boolean=false,val canCancel:Boolean=false)''')
m=m.replace('val customerNote:String,val carrier:String="",val trackingNumber:String="",val trackingUrl:String="",val reviewConsent:Boolean=false,val billing:AccountAddress,val shipping:AccountAddress,val items:List<OrderLineItem>,val notes:List<OrderNote>',
'''val customerNote:String,val carrier:String="",val trackingNumber:String="",val trackingUrl:String="",val reviewConsent:Boolean=false,val canPay:Boolean=false,val canCancel:Boolean=false,val billing:AccountAddress,val shipping:AccountAddress,val items:List<OrderLineItem>,val notes:List<OrderNote>''')
m += '\ndata class OrderPaymentSessionV127(val orderId:Long,val clientSecret:String,val paymentIntentId:String,val paymentToken:String,val publishableKey:String,val mode:String="test")\n'
models.write_text(m)

# API parsing and actions
s=s.replace('o.optString("tracking_url"),o.optBoolean("review_consent"),\n            accountAddress', 'o.optString("tracking_url"),o.optBoolean("review_consent"),o.optBoolean("can_pay"),o.optBoolean("can_cancel"),\n            accountAddress')
s=s.replace('o.optString("tracking_url"),o.optString("carrier"),o.optBoolean("review_consent"))}}', 'o.optString("tracking_url"),o.optString("carrier"),o.optBoolean("review_consent"),o.optBoolean("can_pay"),o.optBoolean("can_cancel"))}}')
insert='''\n    fun orderActionV127(token:String,id:Long,action:String):OrderPaymentSessionV127?{\n        val o=JSONObject(post("$MOBILE/me/orders/$id/action",JSONObject().put("action",action).toString(),token))\n        if(action!="pay")return null\n        return OrderPaymentSessionV127(o.optLong("order_id",id),o.optString("stripe_client_secret"),o.optString("stripe_payment_intent_id"),o.optString("stripe_payment_token"),o.optString("stripe_publishable_key"),o.optString("stripe_mode","test"))\n    }\n'''
s=s.replace('    fun googleLogin(idToken:String):LoginResult{',insert+'\n    fun googleLogin(idToken:String):LoginResult{',1)
p.write_text(s)

# WordPress plugin v1.1.16 + routes/actions
pl=Path('wordpress/autoid-mobile-commerce/autoid-mobile-commerce.php'); php=pl.read_text().replace('Version: 1.1.15','Version: 1.1.16')
php=php.replace("register_rest_route(self::NS, '/me/orders/(?P<id>\\d+)', ['methods'=>'GET','callback'=>[__CLASS__,'me_order_detail'],'permission_callback'=>[__CLASS__,'auth_permission']]);",
"register_rest_route(self::NS, '/me/orders/(?P<id>\\d+)', ['methods'=>'GET','callback'=>[__CLASS__,'me_order_detail'],'permission_callback'=>[__CLASS__,'auth_permission']]);\n        register_rest_route(self::NS, '/me/orders/(?P<id>\\d+)/action', ['methods'=>'POST','callback'=>[__CLASS__,'me_order_action_v127'],'permission_callback'=>[__CLASS__,'auth_permission']]);")

old="'review_consent'=>$o->get_meta('_autoid_review_consent',true)==='yes']+$tracking;"
new="'review_consent'=>$o->get_meta('_autoid_review_consent',true)==='yes','can_pay'=>$o->needs_payment() && !$o->is_paid() && $o->get_payment_method()==='stripe','can_cancel'=>!$o->is_paid() && $o->has_status(['pending','failed','on-hold'])]+$tracking;"
php=php.replace(old,new)
old2="'tracking_url'=>$tracking['tracking_url'],'review_consent'=>$order->get_meta('_autoid_review_consent',true)==='yes','billing'=>$billing"
new2="'tracking_url'=>$tracking['tracking_url'],'review_consent'=>$order->get_meta('_autoid_review_consent',true)==='yes','can_pay'=>$order->needs_payment() && !$order->is_paid() && $order->get_payment_method()==='stripe','can_cancel'=>!$order->is_paid() && $order->has_status(['pending','failed','on-hold']),'billing'=>$billing"
php=php.replace(old2,new2)

action_func=r'''\n    public static function me_order_action_v127(WP_REST_Request $r) {\n        $ok=self::require_wc();if(is_wp_error($ok))return $ok;\n        $uid=absint($r->get_param('_autoid_user_id'));if(!$uid)$uid=self::bearer_user_id($r);\n        $id=absint($r->get_param('id'));$order=$id?wc_get_order($id):null;\n        if(!$order)return new WP_Error('autoid_order_missing','Comanda nu există.',['status'=>404]);\n        if((int)$order->get_customer_id()!==$uid)return new WP_Error('autoid_order_forbidden','Comanda nu aparține contului curent.',['status'=>403]);\n        $b=$r->get_json_params();if(!is_array($b))$b=[];$action=sanitize_key((string)($b['action']??''));\n        if($action==='cancel'){\n            if($order->is_paid()||!$order->has_status(['pending','failed','on-hold']))return new WP_Error('autoid_order_not_cancelable','Comanda nu mai poate fi anulată.',['status'=>409]);\n            $order->update_status('cancelled','Comandă anulată de client din aplicația AutoID.');\n            return rest_ensure_response(['ok'=>true,'order_id'=>$order->get_id(),'status'=>$order->get_status()]);\n        }\n        if($action==='pay'){\n            if($order->is_paid()||!$order->needs_payment())return new WP_Error('autoid_order_not_payable','Comanda nu mai necesită plată.',['status'=>409]);\n            if($order->get_payment_method()!=='stripe')return new WP_Error('autoid_order_payment_method','Plata din aplicație este disponibilă pentru comenzile Stripe.',['status'=>409]);\n            $pi=self::stripe_create_intent_for_order($order);if(is_wp_error($pi))return $pi;\n            $order->add_order_note('Plata a fost reluată de client din aplicația AutoID.');\n            return rest_ensure_response(['ok'=>true,'order_id'=>$order->get_id(),'stripe_publishable_key'=>self::stripe_publishable(),'stripe_client_secret'=>$pi['client_secret'],'stripe_payment_intent_id'=>$pi['payment_intent_id'],'stripe_payment_token'=>$pi['payment_token'],'stripe_mode'=>'test']);\n        }\n        return new WP_Error('autoid_order_action','Acțiune invalidă.',['status'=>400]);\n    }\n'''
php=php.replace('    private static function account_address_payload($customer,$type) {',action_func+'\n    private static function account_address_payload($customer,$type) {',1)
pl.write_text(php)

# Notifications
w=Path('android-v0.1/app/src/main/java/ro/autoid/app/OrderNotificationV126.kt'); ws=w.read_text()
ws=ws.replace('R.drawable.autoid_icon_v100','R.drawable.ic_autoid_notification_v127')
start=ws.index('class OrderNotificationWorkerV126')
ws=ws[:start]+'''class OrderNotificationWorkerV126(appContext:Context,params:WorkerParameters):Worker(appContext,params){override fun doWork():Result{\n    val session=SessionStore(applicationContext);val token=session.accessToken?:return Result.success()\n    val orders=runCatching{AutoIdApi().orders(token)}.getOrElse{return Result.retry()}\n    val prefs=applicationContext.getSharedPreferences("autoid_order_watch_v126",Context.MODE_PRIVATE);val initialized=prefs.getBoolean("initialized",false);val edit=prefs.edit();val now=System.currentTimeMillis()\n    for(o in orders){\n        val base="order_${o.id}_";val oldStatus=prefs.getString(base+"status",null);val oldTracking=prefs.getString(base+"tracking","")?:"";val seen=prefs.getBoolean(base+"seen",false)\n        val created=runCatching{java.time.OffsetDateTime.parse(o.dateCreated).toInstant().toEpochMilli()}.getOrDefault(0L);val recent=created>0L && now-created<48L*60L*60L*1000L\n        val shouldNotifyAwb=o.trackingNumber.isNotBlank()&&oldTracking.isBlank()&&(initialized||seen||recent)\n        if(shouldNotifyAwb){OrderNotificationV126.notify(applicationContext,(o.id%Int.MAX_VALUE).toInt(),"Comanda #${o.number} a plecat din depozitul AutoID","AWB ${o.trackingNumber} a fost generat. Urmărește livrarea.")}\n        if((initialized||seen)&&o.statusCode=="completed"&&oldStatus!="completed"&&o.reviewConsent){OrderNotificationV126.notify(applicationContext,((o.id+100000)%Int.MAX_VALUE).toInt(),"Revizuiește comanda #${o.number}","Cum a fost experiența cu AutoID? Lasă-ne un review pe Google și, dacă dorești, recenzii produselor comandate.",o.id)}else if((initialized||seen)&&oldStatus!=null&&oldStatus!=o.statusCode&&o.statusCode!="completed"&&o.trackingNumber.isBlank()){OrderNotificationV126.notify(applicationContext,((o.id+200000)%Int.MAX_VALUE).toInt(),"Comanda #${o.number} · ${o.status}","Statusul comenzii tale AutoID a fost actualizat.")}\n        edit.putBoolean(base+"seen",true).putString(base+"status",o.statusCode).putString(base+"tracking",o.trackingNumber)\n    }\n    edit.putBoolean("initialized",true).apply();return Result.success()\n}}\n'''
w.write_text(ws)

# Review URL deterministic replacement of the constant line
r=Path('android-v0.1/app/src/main/java/ro/autoid/app/OrderReviewV126.kt'); rs=r.read_text()
lines=rs.splitlines()
for i,line in enumerate(lines):
    if line.startswith('private const val GOOGLE_REVIEW_V126='):
        lines[i]='private const val GOOGLE_REVIEW_V126="https://share.google/9DGE1LfVVLWj7gjjP"'
        break
else:
    raise SystemExit('GOOGLE_REVIEW_V126 constant missing')
r.write_text('\n'.join(lines)+'\n')

# monochrome Android notification small icon, QR-like AutoID mark
res=Path('android-v0.1/app/src/main/res/drawable');res.mkdir(parents=True,exist_ok=True)
(res/'ic_autoid_notification_v127.xml').write_text('''<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24"><path android:fillColor="#FFFFFFFF" android:pathData="M3,3h7v7H3zM5,5v3h3V5zM14,3h7v7h-7zM16,5v3h3V5zM3,14h7v7H3zM5,16v3h3v-3zM13,13h3v3h-3zM17,13h4v2h-4zM17,16h2v2h-2zM20,17h1v4h-4v-2h3zM13,17h3v4h-3z"/></vector>''')

# Order list actions
ux=Path('android-v0.1/app/src/main/java/ro/autoid/app/V114CommerceUx.kt'); u=ux.read_text()
old='''Column(horizontalAlignment=Alignment.End){val visualStatus=orderDisplayStatusV121(o.statusCode,o.trackingNumber,o.status);Text(visualStatus,fontSize=9.sp,fontWeight=FontWeight.Bold,color=if(orderIsTerminalV121(o.statusCode))MaterialTheme.colorScheme.error else C114Good);Text(o.total,fontWeight=FontWeight.ExtraBold,color=C114Ink,fontSize=12.sp);Icon(Icons.Default.ChevronRight,null,tint=C114Muted,modifier=Modifier.size(18.dp))}'''
new='''Column(horizontalAlignment=Alignment.End){val visualStatus=orderDisplayStatusV121(o.statusCode,o.trackingNumber,o.status);Text(visualStatus,fontSize=9.sp,fontWeight=FontWeight.Bold,color=if(orderIsTerminalV121(o.statusCode))MaterialTheme.colorScheme.error else C114Good);Text(o.total,fontWeight=FontWeight.ExtraBold,color=C114Ink,fontSize=12.sp);if(o.canPay||o.canCancel){Row(horizontalArrangement=Arrangement.spacedBy(5.dp)){if(o.canPay)TextButton(onClick={selectedOrderId=o.id}){Text("Plătește",fontSize=9.sp,fontWeight=FontWeight.ExtraBold)};if(o.canCancel)TextButton(onClick={selectedOrderId=o.id}){Text("Anulează",fontSize=9.sp,color=MaterialTheme.colorScheme.error)}}}else Icon(Icons.Default.ChevronRight,null,tint=C114Muted,modifier=Modifier.size(18.dp))}'''
if old not in u: raise SystemExit('order list anchor missing')
u=u.replace(old,new,1);ux.write_text(u)

# Detail actions using Stripe PaymentSheet for an existing unpaid order
od=Path('android-v0.1/app/src/main/java/ro/autoid/app/V120OrderDetail.kt'); t=od.read_text()
t=t.replace('import ro.autoid.app.ui.theme.AutoIdOrange','''import ro.autoid.app.ui.theme.AutoIdOrange\nimport com.stripe.android.PaymentConfiguration\nimport com.stripe.android.paymentsheet.PaymentSheet\nimport com.stripe.android.paymentsheet.PaymentSheetResult\nimport com.stripe.android.paymentsheet.rememberPaymentSheet''')
t=t.replace('import kotlinx.coroutines.withContext','import kotlinx.coroutines.withContext\nimport kotlinx.coroutines.launch')
t=t.replace('    var reload by remember{mutableIntStateOf(0)}\n    val uriHandler=LocalUriHandler.current', '''    var reload by remember{mutableIntStateOf(0)}\n    var actionBusy by remember{mutableStateOf(false)}\n    var actionMessage by remember{mutableStateOf("")}\n    var pendingPayment by remember{mutableStateOf<OrderPaymentSessionV127?>(null)}\n    val context=androidx.compose.ui.platform.LocalContext.current\n    val uriHandler=LocalUriHandler.current\n    val paymentSheet=rememberPaymentSheet{result->when(result){\n        is PaymentSheetResult.Completed->{val p=pendingPayment;if(p!=null){actionBusy=true;actionMessage="Confirmăm plata…"}}\n        is PaymentSheetResult.Canceled->{actionMessage="Plata a fost anulată. Comanda rămâne în așteptare."}\n        is PaymentSheetResult.Failed->{actionMessage=result.error.localizedMessage?:"Plata nu a putut fi finalizată."}\n    }}''')
t=t.replace('    BackHandler(onBack=onBack)\n    LaunchedEffect(orderId,token,reload){', '''    BackHandler(onBack=onBack)\n    LaunchedEffect(actionBusy){if(actionBusy){val p=pendingPayment;if(p!=null){runCatching{withContext(Dispatchers.IO){api.confirmStripePayment(p.orderId,p.paymentIntentId,p.paymentToken,token)}}.onSuccess{ok->if(ok){actionMessage="Plata a fost confirmată.";pendingPayment=null;reload++}else actionMessage="Plata nu este încă confirmată."}.onFailure{actionMessage=it.message?:"Confirmarea plății a eșuat."}};actionBusy=false}}\n    LaunchedEffect(orderId,token,reload){''')
anchor='''                    item{OrderStatusV120(d)}'''
action_ui='''                    item{OrderStatusV120(d)}\n                    if(d.canPay||d.canCancel) item{\n                        OrderSectionV120(Icons.Default.Payments,"Acțiuni comandă"){\n                            if(actionMessage.isNotBlank())Text(actionMessage,fontSize=10.sp,color=if(actionMessage.contains("confirmată"))OrderGood else OrderMuted)\n                            Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){\n                                if(d.canPay)Button(onClick={actionMessage="Pregătim plata securizată…";kotlinx.coroutines.CoroutineScope(Dispatchers.Main).launch{runCatching{withContext(Dispatchers.IO){api.orderActionV127(token,d.id,"pay")}}.onSuccess{p->if(p!=null){pendingPayment=p;PaymentConfiguration.init(context,p.publishableKey);paymentSheet.presentWithPaymentIntent(p.clientSecret,PaymentSheet.Configuration(merchantDisplayName="AutoID Professional Solutions",googlePay=PaymentSheet.GooglePayConfiguration(environment=PaymentSheet.GooglePayConfiguration.Environment.Test,countryCode="RO",currencyCode=d.currency),allowsDelayedPaymentMethods=false))}}.onFailure{actionMessage=it.message?:"Plata nu a putut fi reluată."}}},modifier=Modifier.weight(1f),shape=RoundedCornerShape(10.dp)){Text("Plătește",fontWeight=FontWeight.ExtraBold)}\n                                if(d.canCancel)OutlinedButton(onClick={actionBusy=true;kotlinx.coroutines.CoroutineScope(Dispatchers.Main).launch{runCatching{withContext(Dispatchers.IO){api.orderActionV127(token,d.id,"cancel")}}.onSuccess{actionMessage="Comanda a fost anulată.";reload++}.onFailure{actionMessage=it.message?:"Comanda nu a putut fi anulată."};actionBusy=false}},modifier=Modifier.weight(1f),shape=RoundedCornerShape(10.dp)){Text("Anulează",color=MaterialTheme.colorScheme.error,fontWeight=FontWeight.ExtraBold)}\n                            }\n                        }\n                    }'''
if anchor not in t: raise SystemExit('detail anchor missing')
t=t.replace(anchor,action_ui,1)
od.write_text(t)

print('Applied v1.0.27 order actions, notification fixes and review URL')
