from pathlib import Path
import re

p = Path('android-v0.1/app/src/main/java/ro/autoid/app/V100Screens.kt')
s = p.read_text()

# Root HomeV100 invocation. In V1.0.1 the whole invocation is one line and the
# search callback itself contains V100Tab.Categories. Never use that token as an
# end boundary because it truncates the call before onCart/onRfq/onAi.
root_pos = s.find('HomeV100(')
if root_pos < 0:
    raise SystemExit('HomeV100 root invocation missing')
root_end = s.find('\n', root_pos)
if root_end < 0:
    root_end = min(len(s), root_pos + 12000)
root = s[root_pos:root_end]

# V1.0.1 already wires addRfq in the root call. Only inject it for older layouts
# where it is genuinely missing.
if 'addRfq(' not in root:
    root2, n = re.subn(
        r'(\{\s*ai\s*=\s*true\s*\})',
        r'{ p -> addRfq(p) },\1',
        root,
        count=1
    )
    if n == 0:
        ai_at = root.find('ai=true')
        if ai_at < 0:
            ai_at = root.find('ai = true')
        if ai_at < 0:
            raise SystemExit('HomeV100 root AI callback missing')
        brace = root.rfind('{', 0, ai_at)
        if brace < 0:
            raise SystemExit('HomeV100 root AI lambda start missing')
        root2 = root[:brace] + '{ p -> addRfq(p) },' + root[brace:]
    s = s[:root_pos] + root2 + s[root_end:]

# HomeV100 declaration: add onRfq immediately before onAi only when the previous
# migration has not already done so.
fn_pos = s.find('fun HomeV100(')
if fn_pos < 0:
    raise SystemExit('HomeV100 declaration missing')
fn_body = s.find('{', fn_pos)
if fn_body < 0:
    raise SystemExit('HomeV100 declaration body missing')
head = s[fn_pos:fn_body]
if 'onRfq:' not in head:
    ai_sig = re.search(r'onAi\s*:\s*\(\)\s*->\s*Unit', head)
    if not ai_sig:
        raise SystemExit('HomeV100 onAi signature missing')
    head = head[:ai_sig.start()] + 'onRfq:(Product)->Unit,' + head[ai_sig.start():]
    s = s[:fn_pos] + head + s[fn_body:]

# HomeCard declaration generated by apply_v102: add the real RFQ callback.
hc_pos = s.find('private fun HomeCard(')
if hc_pos < 0:
    raise SystemExit('HomeCard declaration missing')
hc_body = s.find('{', hc_pos)
if hc_body < 0:
    raise SystemExit('HomeCard declaration body missing')
head = s[hc_pos:hc_body]
if 'onRfq:' not in head:
    cart_sig = re.search(r'onCart\s*:\s*\(\)\s*->\s*Unit', head)
    if not cart_sig:
        raise SystemExit('HomeCard onCart signature missing')
    insert_at = cart_sig.end()
    head = head[:insert_at] + ',\n    onRfq: () -> Unit' + head[insert_at:]
    s = s[:hc_pos] + head + s[hc_body:]

# The two Home lists in V1.0.1 already pass onRfq. Preserve them. If a prior
# layout has only an onCart callback, add the matching RFQ callback.
s = s.replace(
    '{onFavorite(p)},{onCart(p)})',
    '{onFavorite(p)},{onCart(p)},{onRfq(p)})'
)
s = s.replace(
    '{ onFavorite(p) }, { onCart(p) })',
    '{ onFavorite(p) }, { onCart(p) }, { onRfq(p) })'
)
s = s.replace(
    'HomeCard(r,commerce.isFavorite(r.id),{onOpen(r)},{onFavorite(r)},{onCart(r,1)})',
    'HomeCard(r,commerce.isFavorite(r.id),{onOpen(r)},{onFavorite(r)},{onCart(r,1)},{onRfq(r,1)})'
)
s = s.replace(
    'HomeCard(r, commerce.isFavorite(r.id), { onOpen(r) }, { onFavorite(r) }, { onCart(r,1) })',
    'HomeCard(r, commerce.isFavorite(r.id), { onOpen(r) }, { onFavorite(r) }, { onCart(r,1) }, { onRfq(r,1) })'
)

# Recommendation/liquidation calls can be compact. Add RFQ only if absent.
s = re.sub(
    r'HomeCard\((p|o),([^\n]*?),\{onFavorite\(\1\)\},\{onCart\(\1\)\}\)',
    lambda m: 'HomeCard(' + m.group(1) + ',' + m.group(2) + ',{onFavorite(' + m.group(1) + ')},{onCart(' + m.group(1) + ')},{onRfq(' + m.group(1) + ')})',
    s
)

# The RFQ button inside HomeCard must invoke RFQ, never product navigation.
hc_pos = s.find('private fun HomeCard(')
hc_end = s.find('@Composable', hc_pos + 20)
if hc_end < 0:
    hc_end = len(s)
hc = s[hc_pos:hc_end]
label_at = hc.find('Text("Cerere ofertă"')
if label_at >= 0:
    button_at = hc.rfind('OutlinedButton(', 0, label_at)
    if button_at >= 0:
        action_at = hc.find('onClick', button_at, label_at)
        eq_at = hc.find('=', action_at, label_at) if action_at >= 0 else -1
        comma_at = hc.find(',', eq_at, label_at) if eq_at >= 0 else -1
        if action_at >= 0 and eq_at >= 0 and comma_at >= 0:
            hc = hc[:eq_at + 1] + ' onRfq' + hc[comma_at:]
s = s[:hc_pos] + hc + s[hc_end:]

p.write_text(s)
print('Wired v1.0.2 Home RFQ callbacks with full HomeV100 call boundary')
