plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.plugin.compose")
}

android {
    namespace = "ro.autoid.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "ro.autoid.app"
        minSdk = 23
        targetSdk = 36
        versionCode = 13100
        versionName = "1.0.28"
    }

    signingConfigs {
        getByName("debug") {
            storeFile = file("../autoid-dev.keystore")
            storePassword = "autoiddev2026"
            keyAlias = "autoiddev"
            keyPassword = "autoiddev2026"
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures { compose = true }
    packaging { resources.excludes += "/META-INF/{AL2.0,LGPL2.1}" }
}

// v0.4 migration shim: keep v0.3 MainActivity stable while routing only the product screen
// to the new, independently maintained ProductFamilyScreen. The release source package
// generated by CI contains the migrated call after this step runs.
tasks.named("preBuild").configure {
    doFirst {
        val main = file("src/main/java/ro/autoid/app/MainActivity.kt")
        val oldCall = "        ProductDetail(\n            seed = selectedProduct!!,"
        val newCall = "        ProductFamilyScreen(\n            seed = selectedProduct!!,"
        val source = main.readText()
        if (source.contains(oldCall)) main.writeText(source.replace(oldCall, newCall))
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.16.0")
    implementation("androidx.activity:activity-compose:1.10.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.9.1")
    implementation("androidx.compose.ui:ui:1.8.3")
    implementation("androidx.compose.ui:ui-tooling-preview:1.8.3")
    implementation("androidx.compose.foundation:foundation:1.8.3")
    implementation("androidx.compose.material3:material3:1.3.2")
    implementation("androidx.compose.material:material-icons-extended:1.7.8")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2")
    implementation("io.coil-kt:coil-compose:2.7.0")
    implementation("com.google.android.gms:play-services-code-scanner:16.1.0")
    implementation("androidx.credentials:credentials:1.6.0")
    implementation("androidx.credentials:credentials-play-services-auth:1.6.0")
    implementation("com.google.android.libraries.identity.googleid:googleid:1.2.0")
    implementation("com.stripe:stripe-android:22.6.1")
    implementation("androidx.work:work-runtime-ktx:2.10.1")
    implementation(platform("com.google.firebase:firebase-bom:34.18.0"))
    implementation("com.google.firebase:firebase-messaging")
    debugImplementation("androidx.compose.ui:ui-tooling:1.8.3")
}
